FROM kiesun/kieq_build:latest AS builder

WORKDIR /root

RUN git clone https://github.com/KieQ/kies-code-frontend.git

WORKDIR /root/kies-code-frontend

RUN sh script/build.sh

FROM nginx:latest

COPY --from=builder /root/kies-code-frontend/app/dist/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

COPY default.conf.template /etc/nginx/conf.d/default.conf.template

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
