FROM kiesun/kieq_build_arm:latest AS builder

WORKDIR /root

RUN git clone https://github.com/KieQ/kies-code-backend.git

WORKDIR /root/kies-code-backend

RUN sh script/build.sh

FROM ubuntu:latest

COPY --from=builder /root/kies-code-backend/kies /root

COPY --from=builder /lib/arm-linux-gnueabihf/libasan.so.5 /lib/arm-linux-gnueabihf

CMD /root/kies
